const SET_USER = 'SET_USER';
const REMOVE_USER = 'REMOVE_USER';
const SET_SCHEDULES = 'SET_SCHEDULES';
const SET_SELECTED_SCHEDULE = 'SET_SELECTED_SCHEDULE';
const SET_SEATS = 'SET_SEATS';

export {
  SET_USER,
  REMOVE_USER,
  SET_SCHEDULES,
  SET_SELECTED_SCHEDULE,
  SET_SEATS,
};
