const SET_USER = 'SET_USER';
const SET_DATE = 'SET_DATE';
const SET_ERROR = 'SET_ERROR';
const SET_SEATS = 'SET_SEATS';
const RESET_ERROR = 'RESET_ERROR';
const REMOVE_USER = 'REMOVE_USER';
const SELECT_SEATS = 'SELECT_SEATS';
const SET_LOADING = 'SET_LOADING';
const RESET_LOADING = 'RESET_LOADING';
const SET_SCHEDULES = 'SET_SCHEDULES';
const SET_SELECTED_SCHEDULE = 'SET_SELECTED_SCHEDULE';
const SET_FILTERED_SCHEDULES = 'SET_FILTERED_SCHEDULES';

export {
  SET_USER,
  SET_DATE,
  SET_ERROR,
  SET_SEATS,
  RESET_ERROR,
  REMOVE_USER,
  SELECT_SEATS,
  SET_LOADING,
  RESET_LOADING,
  SET_SCHEDULES,
  SET_FILTERED_SCHEDULES,
  SET_SELECTED_SCHEDULE,
};
